### ISSUE TITLE
1. funkcna verzia

### ISSUE THREAD

**Issue by jankelemen** [TIS2021-FMFI/osciloskop#25]
mala by vediet robit raw a average

**Comment by pavelpetrovic** [comment]
v hpctrl repozitari je aktualizovana verzia, ktora nacitava z viacerych kanalov, ako sme sa dohodli.
v rezime cmd pribudol prikaz na prepinanie aktivnych kanalov - je to nejaka kombinacia cisel 1234.
napriklad prikaz 
2
nastavi iba 2. kanal alebo prikaz
234
nastavi tri kanaly 2,3 a 4.

skompilovanu verziu som dal na https://kempelen.dai.fmph.uniba.sk/files/hpctrl.zip
(ale asi k tomu treba este DLL-ka z visual studia)
