### ISSUE TITLE
urobit pouzivatelsky manual

### ISSUE THREAD

**Issue by jankelemen** [TIS2021-FMFI/osciloskop#64]
dr. Petrovic chcel, aby sme urobili manual pre ludi, co budu nasu aplikaciu pouzivat. Mali by tam byt obrazky a kazdy panel popisany, ze naco aka funkcionalita sluzi

**Comment by YelovSK** [comment]
https://github.com/TIS2021-FMFI/osciloskop/commit/2bb0c3cb386baf0e993ddbe15a21a8326deeecc2
