### ISSUE TITLE
vytvorit subor technicka dokumentacia

### ISSUE THREAD

**Issue by jankelemen** [TIS2021-FMFI/osciloskop#65]
subor technicka dokumentacia by mal obsahovat katalog poziadaviek, navrh a testovacie
scenare. Tento subor treba dat do docs vetvy. V tejto vetve by potom mala byt dokumentacia vo finalnej podobe

**Comment by pavelpetrovic** [comment]
predpokladam, ze toto bolo davno urobene, preco to visi stale v TODO?
